version: '3.6'
services:
  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile-dev
    volumes:
      - './services/client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
      - REACT_APP_CSRF_TOKEN=${REACT_APP_CSRF_TOKEN}
      - REACT_APP_DOMAIN_NAME=${REACT_APP_DOMAIN_NAME}
      - REACT_APP_TWITCH_OAUTH_LINK=${REACT_APP_TWITCH_OAUTH_LINK}
      - REACT_APP_TWITCH_CLIENT_ID=${REACT_APP_TWITCH_CLIENT_ID}
      - REACT_APP_TWITCH_USER_NAME=${REACT_APP_TWITCH_USER_NAME}
      - REACT_APP_TWITCH_OAUTH_TOKEN=${REACT_APP_TWITCH_OAUTH_TOKEN}
      - REACT_APP_TWITCH_CHANNEL_NAME=${REACT_APP_TWITCH_CHANNEL_NAME}
    depends_on:
      - users
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 80:80
    depends_on:
      - users
      - client
  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile-dev
    expose:
      - 5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - SECRET_KEY=my_precious
    depends_on:
      - users-db
  users-db:
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


