###########
# BUILDER #
###########
# base image
FROM node:10.4.1-alpine as builder

# set working directory
WORKDIR /usr/src/app

# create build
COPY . /usr/src/app

# install app dependencies
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json /usr/src/app/package.json
RUN npm install

RUN npm install terser@3.14.1 --save-dev
RUN npm run build

#########
# FINAL #
#########

# base image
FROM nginx:1.15.0-alpine

# update nginx conf
RUN rm -rf /etc/nginx/conf.d
COPY conf /etc/nginx

# copy static files
COPY --from=builder /usr/src/app/build /usr/share/nginx/html

# expose port
EXPOSE 80

# run nginx
CMD ["nginx", "-g", "daemon off;"]
